# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 23:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign_up_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
