# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_sign_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='minor_bday',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='minor_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
